### 获取所有服务实例
GET http://localhost:8484/findAll?service=app1_public_dev_com.bruce.durpc.demo.api.UserService

### 注册实例
POST http://localhost:8484/reg?service=com.bruce.durpc.UserService
content-type: application/json

{
  "context": "durpc",
  "host": "127.0.0.1",
  "port": 8081,
  "scheme": "http",
  "status": false,
  "parameters": {
    "env": "dev",
    "tag": "RED"
  }
}

### 删除实例
POST http://localhost:8484/unreg?service=com.bruce.durpc.UserService
content-type: application/json

{
  "context": "durpc",
  "host": "127.0.0.1",
  "port": 8082,
  "scheme": "http"
}

### 实例8082保活
POST http://localhost:8484/renew?service=com.bruce.durpc.UserService
content-type: application/json

{
  "context": "durpc",
  "host": "127.0.0.1",
  "port": 8082,
  "scheme": "http"
}


### 获取服务实例版本
GET http://localhost:8484/version?service=com.bruce.durpc.UserService

### info
GET http://localhost:8484/info

### cluster
GET http://localhost:8484/cluster

### sl 85
GET http://localhost:8485/sl


